Лабораторна Робота №4

Завдання. Торговельне підприємство планує продаж сезонних товарів на ринках, враховуючи можливі варіанти купівельного попиту ( П1, П2, П3, П4, П5) − дуже низький, низький, середній, високий та дуже високий. На підприємстві розроблено чотири господарських стратегії продажу товарів
( А1, А2, А3, А4). Товарообіг, що залежить від стратегій підприємства й купівельного попиту, представлено у вигляді платіжної матриці.

Платіжна матриця
   П1	              П2	              П3	         П4	               П5
A1	180	           140          	  k  	         (245 − 4k)	      232
A2	420	           (120+10k)	        140          220	            100
A3	(25 + 8k)	     315	              35	         49                (10(k + 23) − 50)
A4	(290−10k)	     k                 9     	      (100k − 90)       201

Потрібно знайти оптимальну стратегію поведінки торговельного підприємства, використовуючи критерії  песимізму, оптимізму, Гурвіца 
(λ = 1/k+3 при k = [1, 12];  λ = 4/k при k = [13, 26]), Лапласа, Байєса-Лапласа (p1= 0,1 p2 = 0,2  p3 = λ p4 = λ + 0,1 p5 = 1 − p1 − p2 − p3 − p4 )
 та Ходжа-Лемана.


Згідно моєму варінту, k = 7. Знаходимо показник оптимізму, створуємо задану матрицю платежів, та масив ймовірністей виникнення всіх станів.

In [64]:
import numpy as np
k = 7

if k >= 1 | k <= 12: 
    optimism_indic = 1 / (k + 3)
else:
    optimism_indic = 4 / k

payment_matrix = np.array([
    [180, 140, k, (245-4*k), 232],
    [420, (120+10*k), 140, 220, 100],
    [(25+8*k), 315, 35, 49, (10*(k+23)-50)],
    [(290-10*k), k, 9, (100*k-90), 201]
])

candidates = ['A1', 'A2', 'A3', 'A4']

p = [0.1, 0.2, optimism_indic, optimism_indic + 0.1, 0.6 - 2 * optimism_indic]

print("Матриця платежів:")
for i in range(0, len(payment_matrix)):
    print(payment_matrix[i])


Матриця платежів:
[180 140   7 217 232]
[420 190 140 220 100]
[ 81 315  35  49 250]
[220   7   9 610 201]


Критерій песимізму. Вибирається така стратегія, яка забезпечує
найкращий з найгірших результатів.


In [65]:
pessimism_results = [min(alternate) for alternate in payment_matrix]

best_result_pess = max(pessimism_results)
best_index_pess = pessimism_results.index(max(pessimism_results))
best_name_pess = candidates[best_index_pess]

print("Масив мінімальних значень:", pessimism_results)
print(f"Найкраща альтернатива за критерієм песимізму (максимальне значення): {best_name_pess} - {best_result_pess}")

Масив мінімальних значень: [7, 100, 35, 7]
Найкраща альтернатива за критерієм песимізму (максимальне значення): A2 - 100


Критерій оптимізму. зорієнтований на мінімізацію жалю із приводу втраченого прибутку й
допускає розумний ризик заради отримання додаткового прибутку. Обираємо рішення, за якого максимальний жаль буде меншим, ніж за
інших рішень:

In [66]:
payment_matrix_transp = payment_matrix.transpose();
max_in_col = [max(alternate) for alternate in payment_matrix_transp]

matrix_loses = [max_in_col - payment_matrix]
for i in range(0, len(matrix_loses)):
   print("Матриця програшів:\n", matrix_loses[i])

optimism_results = [max(value) for value in matrix_loses[0]]

best_result_opt = min(optimism_results)
best_index_opt = optimism_results.index(min(optimism_results))
best_name_opt = candidates[best_index_opt]

print("Масив максимальних значень:", optimism_results)
print(f"Найкраща альтернатива за критерієм оптимізму (мінімальне значення): {best_name_opt} - {best_result_opt}")

Матриця програшів:
 [[240 175 133 393  18]
 [  0 125   0 390 150]
 [339   0 105 561   0]
 [200 308 131   0  49]]
Масив максимальних значень: [393, 390, 561, 308]
Найкраща альтернатива за критерієм оптимізму (мінімальне значення): A4 - 308


Критерій Гурвіца. Цей
критерій рекомендує в процесі прийняття рішення використовувати
певний середній результат, що характеризує стан між крайнім песимізмом
і крайнім оптимізмом.
У випадку, коли гру задано матрицею виграшів за критерієм Гурвіца
перевага віддається варіанту рішення, яке визначається максимумом серед
лінійних комбінацій мінімального і максимального виграшів.


In [67]:
gurvitz_results = [(optimism_indic * min(alternate) + (1 - optimism_indic) * max(alternate)) for alternate in payment_matrix]

best_result_gurvitz  = max(gurvitz_results)
best_index_gurvitz = gurvitz_results.index(max(gurvitz_results))
best_name_gurvitz= candidates[best_index_gurvitz]

print("Масив утворених результатів:", gurvitz_results)
print(f"Найкраща альтернатива за критерієм Гурвіца (максимальне значення): {best_name_gurvitz} - {best_result_gurvitz}")

Масив утворених результатів: [209.5, 388.0, 287.0, 549.7]
Найкраща альтернатива за критерієм Гурвіца (максимальне значення): A4 - 549.7


Критерій Лапласа. Дозволяє
відокремити кращий варіант у тому випадку, якщо жодна з умов не має
істотної переваги.
Коли немає ніяких підстав вважати, що кожний окремий стан
природи більш імовірний у порівнянні з іншими, використовують
припущення про те, що імовірність виникнення кожного з можливих
станів оточуючого середовища однакова. Тоді оцінку середньої цінності
кожної альтернативи можна обчислити за формулою звичайного
середнього арифметичного всіх її можливих оцінок у різних станах
природи. Оптимальною є та альтернатива, яка має найбільшу середню
оцінку

In [68]:
laplas_results = [sum(alternate) / len(alternate) for alternate in payment_matrix]

best_result_laplas  = max(laplas_results)
best_index_laplas = laplas_results.index(max(laplas_results))
best_name_laplas = candidates[best_index_laplas]

print("Масив утворених результатів:", laplas_results)
print(f"Найкраща альтернатива за критерієм Лапласа (максимальне значення): {best_name_laplas} - {best_result_laplas}")

Масив утворених результатів: [155.2, 214.0, 146.0, 209.4]
Найкраща альтернатива за критерієм Лапласа (максимальне значення): A2 - 214.0


Критерій Байеса-Лапласа

In [69]:
bayes_laplas_results = [sum(value * probability for value, probability in zip(alternate, p)) for alternate in payment_matrix]

best_result_bayes_laplas  = max(bayes_laplas_results)
best_index_bayes_laplas = bayes_laplas_results.index(max(bayes_laplas_results))
best_name_bayes_laplas = candidates[best_index_bayes_laplas]

print("Масив утворених результатів:", bayes_laplas_results)
print(f"Найкраща альтернатива за критерієм Байєса-Лапласа (максимальне значення): {best_name_bayes_laplas} - {best_result_bayes_laplas}")

Масив утворених результатів: [182.9, 178.0, 184.39999999999998, 226.7]
Найкраща альтернатива за критерієм Байєса-Лапласа (максимальне значення): A4 - 226.7


 Критерій Ходжа-Лемана. Є комбінацією критеріїв Байєса-Лапласа і Вальда із показником оптимізму є [0; 1], що характеризує ступінь довіри ОПР до імовірнісного розподілу виникнення можливих станів природи. 

In [70]:
khoj_lehman_results = [ (1 - optimism_indic) * min(value) + optimism_indic * bayes_laplas_result  for bayes_laplas_result, value in zip(bayes_laplas_results, payment_matrix)]

best_result_khoj_lehman  = max(khoj_lehman_results)
best_index_khoj_lehman = khoj_lehman_results.index(max(khoj_lehman_results))
best_name_khoj_lehman = candidates[best_index_khoj_lehman]

print("Масив утворених результатів:", khoj_lehman_results)
print(f"Найкраща альтернатива за Критерієм Ходжа-Лемана (максимальне значення) (λ = {optimism_indic}): {best_name_khoj_lehman} - {best_result_khoj_lehman}")

Масив утворених результатів: [24.590000000000003, 107.8, 49.94, 28.970000000000002]
Найкраща альтернатива за Критерієм Ходжа-Лемана (максимальне значення) (λ = 0.1): A2 - 107.8
