Лабораторна робота №8.

Варіант № 7.


ЗАДАЧА  3.

3	12	9	1	7	350<br>
2	4	11	2	10	330<br>
7	14	12	5	8	270<br>
210	170 220	150	200	<br>

Метод північно-західного кута.

In [286]:
import numpy as np
import openpyxl


def getMatrixOutOfSheet(sheet):
   matrix = []

   for row in sheet.iter_rows(values_only = True):
      matrix.append(row)

   return np.array(matrix)


def northwest_corner_method(supply, demand):
   rows, cols = len(supply), len(demand)
   allocations = np.zeros((rows, cols))
   
   i, j = 0, 0
   
   while i < rows and j < cols:
      quantity = min(supply[i], demand[j])
      allocations[i, j] = quantity
      supply[i] -= quantity
      demand[j] -= quantity

      if supply[i] == 0:
         i += 1

      if demand[j] == 0:
         j += 1

   return allocations

In [287]:
filePath = 'satpr8.xlsx'
workbook = openpyxl.load_workbook(filePath)

sheet = workbook['laba8']

matrix = []

matrix = getMatrixOutOfSheet(sheet)

supply = matrix[:-1, -1]
demand = matrix[-1, :-1]
costs = matrix[:-1, :-1]

allocations = northwest_corner_method(supply, demand)
print("Allocations:\n",allocations)

total_cost = np.sum(allocations * costs)
print("\nTotal Cost:",total_cost)


Allocations:
 [[210. 140.   0.   0.   0.]
 [  0.  30. 220.  80.   0.]
 [  0.   0.   0.  70. 200.]]

Total Cost: 6960.0
